version: "3.8"

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: pg_passWRD
            POSTGRES_USER: admin
            PGDATA: /mnt/postgres/data
        ports:
            - "5432:5432"
        volumes:
            - type: bind
              source: ./postgres
              target: /mnt/postgres
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@machine.local
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_DEFAULT_SERVER: db
        ports:
            - "8080:80"
        volumes:
            - type: bind
              source: ./pgadmin
              target: /var/lib/pgadmin
        depends_on: 
            - db
        logging:
            driver: none
