version: "3.8"

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: pg_passWRD
            POSTGRES_USER: admin
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@machine.local
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_DEFAULT_SERVER: db
        ports:
            - "8080:80"
        volumes:
            - type: bind
              source: ./pgadmin
              target: /var/lib/pgadmin
